
devtools::install_github("JamesStimson/transcluster", build_vignettes =T)
library(transcluster)
#vignette("how-to-guide", package = "transcluster")
library(data.table)
library(stats)
library(clue)
library(igraph)
library(stringr)
library(BiocManager)
library(dplyr)
library(ggplot2)

packageVersion("transcluster") # 0.1.0
packageVersion("stats") # 4.1.0
packageVersion("clue") # 0.3.64
packageVersion("igraph") # 1.4.2
packageVersion("stringr") # 1.5.0
packageVersion("ggplot2") # 3.4.2

dataset = "B2" # phylogroup - change to A, B1, B2, C, D, E, G

# read in CSV table from VCF
snpMatrix <- data.frame(read.csv(paste(dataset,".matrix.csv",sep=""),sep="\t"))
snpMatrix <- snpMatrix[,-c(1)] #  
dim(snpMatrix) #  should be square
names1 <- colnames(snpMatrix)
snpMatrix2 <- matrix(unlist(snpMatrix), ncol=dim(snpMatrix)[2], byrow=T)
colnames(snpMatrix2) <- names1
rownames(snpMatrix2) <- names1

# get date info
xx<-data.frame(read.csv("05312023_isolatelistfortranscluster.csv"))
# 152 samples x 5 variables: 
# Assembly_Name Source Phylogroup Date_Collection Farm.Name
xx$Assembly_Name <-  gsub('_', '\\.',xx$Assembly_Name) # fix name

dates3 <- c()
for (i2 in 1:length(colnames(snpMatrix))){
  colnames(snpMatrix)[i2]
  for (i in 1:length(rownames(xx))){
      if(colnames(snpMatrix)[i2] == xx$Assembly_Name[i]){
         dates3 <- c(dates3, xx$Date_Collection[i]) } 
   } # double for because I can check what it is doing ...
}

# set up initial mode without parameters yet
myModel <- createModel(colnames(snpMatrix) , dates3, round(snpMatrix2))

for (beta1 in c(5.5,5,4.5)){
for (lambda1 in c(0.68, 0.63, 0.58)){

#beta1=5.5
#lambda1=0.68
  print("Doing")
  print(beta1)
  print(lambda1)
# beta = serial transmission interval, transmissions/year = 4.5 / 5.5 / 6.5
# lambda = mutation rate - SNPs/core/year - 0.29-0.68

myModel <- setParams(myModel, lambda=lambda1, beta=beta1)
myModel <- setSNPThresholds(myModel, c(3,6,9))
mySNPClusters <- makeSNPClusters(myModel, 'test') # Create the clusters:
myModel <- setTransThresholds(myModel, c(5,10,15))
myTransClusters <- makeTransClusters(myModel, 'test')
myModel <- setCutoffs(myModel)

pdf(paste(dataset,"_SNP_hist.pdf",sep=""), width=8, height=8) # plot SNPs 
hist(myModel$snp, breaks=42000 ,xlab="Numbers of SNPs", ylab="Frequency",
     col="grey", xlim=c(0,10))  
dev.off()

pdf(paste(dataset,".heatmap.pdf",sep=""), width=11, height=11) # plot heatmap 
heatmap(myModel$snp , col=heat.colors(12), scale="column", cexRow=1, cexCol=1,
        margins=c(15,16))
legend(x="topleft", legend=c("min","ave","max"), fill=heat.colors(12),cex=1.1)
dev.off()

pdf(paste(dataset,'_SNPclusters_',lambda1,'_',beta1,'.pdf',sep = ""),
    width=16, height=16) # plot SNP-based clusters - not the key plots 
par(mfrow=c(2,2))
for (i in 1:4){ 
    plotSNPClusters(myModel, vColor='orange', vSize=5,   level=i,
                      labelOffset=0.5) } 
dev.off()

# plotTransClusters(myModel, vSize=3, vFontSize=1, level=24, thick=0.5)
                  
pdf(paste(dataset,'_Transmission_model_',lambda1,'_',beta1,'.pdf',sep = ""),
    width=16, height=16) # plot transmission  - these are the key plots
par(mfrow=c(2,2))
for (i in c(7,12,18,24)){ 
    plotTransClusters(myModel, vSize=5,   level=i,  
                      labelOffset=0.2,  vColor = "lightblue") }
dev.off()

### ### now get pattern of transmissions from transmission plots

set_G1 <- data.frame( )
for (i in 7:24){ 
  temp1 <- as.data.frame(get.edgelist(plotTransClusters(myModel,level=i)))  
  temp1$stage = rep(i,length(temp1$V1)) 
  set_G1 <- rbind(set_G1, temp1)   }
colnames(set_G1) <- c("A","B","Stage")

set_G1_1 <- data.frame(1,1,1)
colnames(set_G1_1) <- c("A","B","Stage")
for (i in 1:length(set_G1$A)){ # for each row
    new1=1 # tag
    for (i2 in 1:length(set_G1_1$A)){ # for each new row
        if( ((set_G1$A[i] == set_G1_1$A[i2]) && 
             (set_G1$B[i] == set_G1_1$B[i2])) ||
            ((set_G1$B[i] == set_G1_1$A[i2]) && 
             (set_G1$A[i] == set_G1_1$B[i2])) ){
          new1=0 # not new
        } # end if
    } # end for each new row
    if(new1==1){ set_G1_1 <- rbind(set_G1_1, set_G1[i,])}
} # end for each old row
set_G1_1 <- set_G1_1[-c(1),]
write.csv(set_G1_1, paste(dataset, '_transcluster_order_',lambda1,'_',
                          beta1,'.csv',sep = ""))

# make plot of connections vs threshold limit
# convert igraph object to dataframe, then count connections

if(lambda1==0.58){  # lambda1 in c(0.29, 0.3875, 0.485, 0.5825, 0.68)
  num_G1 <- c()
  for (i in 7:24){ 
  temp1 <- tryCatch( 
    { dim(as.data.frame(get.edgelist(plotTransClusters(myModel,level=i))))[1] },
   error = function(e) { 0 } )
  num_G1 <- c(num_G1, temp1) } }

if(lambda1==0.63){ 
  num_G1_4 <- c()
  for (i in 7:24){ 
  temp1 <- tryCatch( 
    { dim(as.data.frame(get.edgelist(plotTransClusters(myModel,level=i))))[1] },
   error = function(e) { 0 } )
  num_G1_4 <- c(num_G1_4, temp1) }  }

if(lambda1==0.68){ 
  num_G1_5 <- c()
  for (i in 7:24){ 
  temp1 <- tryCatch( 
    { dim(as.data.frame(get.edgelist(plotTransClusters(myModel,level=i))))[1] },
   error = function(e) { 0 } )
  num_G1_5 <- c(num_G1_5, temp1) }   }
 }  # lamdba

# make plot
pdf(paste(dataset,'_Connections_',beta1,'.pdf',sep = ""),
    width=8, height=8)
plot(7:24, num_G1, xlab="Threshold", ylab="Connections", col="pink", cex=2,
     cex.axis=1.4, cex.lab=1.4, ylim=c(0,10))
lines(7:24, num_G1, lwd=2, col="pink")  + grid()
points(7:24, num_G1_4, col="blue", cex=2) 
lines(7:24, num_G1_4, lwd=2, col="blue", lty="dotted")  
points(7:24, num_G1_5, col="grey", cex=2) 
lines(7:24, num_G1_5, lwd=2, col="grey", lty="dotdash")  
legend("topleft",  lwd=2,
       lty=c("solid","dashed","dotdash","dotted","solid"),
       cex=1.4, title="     u   T",
       col=c("pink","blue","grey"),
       legend=c(paste("0.48",beta1,sep=" "),
                paste("0.58",beta1,sep=" "),
                paste("0.68",beta1,sep=" ")))
dev.off()

}  # end for loop beta1
quit()
y